#ifndef SIMPLE_INTEROP_H
#define SIMPLE_INTEROP_H
#include "../interop.h"

constexpr int BINDING_MATERIAL_BASETEXTURE = LAST_SHARED_BINDING + 1;

constexpr int CID_ANIMATION_FRAME_BLENDING = LAST_SHARED_CID + 1;
constexpr int CID_SPLIT_PIXELS = CID_ANIMATION_FRAME_BLENDING + 1;

constexpr int CID_BASETEXTURE_MODE = CID_TEXTURE_MODE_START + BINDING_MATERIAL_BASETEXTURE;

#endif